# -*- coding: utf-8 -*-
"""weakly project 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145Dnu5OnCsTPARR6rXojnRqQTTSuKWGK
"""

pip install faker

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

num_students = 250

student_ids = [f'S{i:03d}' for i in range(1, num_students + 1)]
names = [fake.name() for _ in range(num_students)]
genders = np.random.choice(['Male', 'Female'], num_students)
departments = np.random.choice(['CSE', 'IT', 'ECE'], num_students)
years = np.random.choice(['1st', '2nd', '3rd'], num_students)
maths_marks = np.random.randint(40, 100, num_students)
science_marks = np.random.randint(40, 100, num_students)
english_marks = np.random.randint(40, 100, num_students)
attendance = np.random.randint(50, 101, num_students)
internal_marks = np.random.randint(0, 26, num_students)

students_data = pd.DataFrame({
    'Student_ID': student_ids,
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths_marks,
    'Science': science_marks,
    'English': english_marks,
    'Attendance (%)': attendance,
    'Internal Marks': internal_marks
})

display(students_data)

# Convert the dictionary to a pandas DataFrame
# The 'data' dictionary is assumed to be available from previous cells.
df = pd.DataFrame(data)

print("--- Data Cleaning and Preprocessing ---")

# Check for missing values
print("\nChecking for missing values:")
print(df.isnull().sum())

# Check data types
print("\nChecking data types:")
df.info()

# Display first few rows of the DataFrame
print("\nFirst 5 rows of the DataFrame:")
print(df.head())

import numpy as np
import pandas as pd
from faker import Faker

fake = Faker()

data = {
    "Student_ID": np.random.randint(0, 10, 250),
    "Name": [fake.name() for _ in range(250)],
    "Gender": np.random.choice(["Male", "Female"], 250),
    "Department": np.random.choice(["CSE", "IT", "ECE"], 250),
    "Year": np.random.choice([1, 2, 3, 4], 250),
    "Maths": np.random.randint(40, 100, 250),
    "Science": np.random.randint(40, 100, 250),
    "English": np.random.randint(40, 100, 250),
    "Attendance": np.random.randint(50, 100, 250),
    "Internal_Marks": np.random.randint(0, 25, 250)
}



"""### Relationship Between Variables"""

# Relationship: Attendance vs. Marks
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Attendance', y='Average_Marks', data=df, hue='Grade', palette='viridis', s=100, alpha=0.7)
plt.title('Attendance vs. Average Marks')
plt.xlabel('Attendance (%)')
plt.ylabel('Average Marks')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

print(f"Correlation between Attendance and Average Marks: {df['Attendance'].corr(df['Average_Marks']):.2f}")

# Relationship: Internal marks vs. Final performance (Average Marks)
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Internal_Marks', y='Average_Marks', data=df, hue='Grade', palette='plasma', s=100, alpha=0.7)
plt.title('Internal Marks vs. Average Marks')
plt.xlabel('Internal Marks')
plt.ylabel('Average Marks')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

print(f"Correlation between Internal Marks and Average Marks: {df['Internal_Marks'].corr(df['Average_Marks']):.2f}")

"""### Group-Based Analysis"""

# Department-wise Performance
department_performance = df.groupby('Department')['Average_Marks'].mean().sort_values(ascending=False)
print("\n--- Department-wise Average Marks ---")
print(department_performance)

plt.figure(figsize=(8, 5))
sns.barplot(x=department_performance.index, y=department_performance.values, palette='viridis')
plt.title('Average Marks by Department')
plt.xlabel('Department')
plt.ylabel('Average Marks')
plt.ylim(0, 100) # Set y-axis limits to 0-100 for marks
plt.show()

# Gender-wise Comparison
gender_comparison = df.groupby('Gender')['Average_Marks'].mean().sort_values(ascending=False)
print("\n--- Gender-wise Average Marks ---")
print(gender_comparison)

plt.figure(figsize=(6, 4))
sns.barplot(x=gender_comparison.index, y=gender_comparison.values, palette='plasma')
plt.title('Average Marks by Gender')
plt.xlabel('Gender')
plt.ylabel('Average Marks')
plt.ylim(0, 100)
plt.show()

# Year-wise Trends
year_trends = df.groupby('Year')['Average_Marks'].mean().sort_values(ascending=True)
print("\n--- Year-wise Average Marks ---")
print(year_trends)

plt.figure(figsize=(8, 5))
sns.lineplot(x=year_trends.index, y=year_trends.values, marker='o', color='green')
plt.title('Average Marks by Academic Year')
plt.xlabel('Year')
plt.ylabel('Average Marks')
plt.ylim(0, 100)
plt.xticks(year_trends.index) # Ensure all years are shown on x-axis
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""### Identifying Top and Low Performing Students"""

# Identify Top Performing Students (Grade 'A')
top_performers = df[df['Grade'] == 'A'].sort_values(by='Average_Marks', ascending=False)
print("\n--- Top Performing Students ---")
display(top_performers[['Name', 'Department', 'Year', 'Total_Marks', 'Average_Marks', 'Grade']].head())

# Identify Low Performing Students (Grade 'F')
low_performers = df[df['Grade'] == 'F'].sort_values(by='Average_Marks', ascending=True)
print("\n--- Low Performing Students ---")
display(low_performers[['Name', 'Department', 'Year', 'Total_Marks', 'Average_Marks', 'Grade']].head())

"""### Student Performance Analysis"""

# Calculate Total Marks
df['Total_Marks'] = df['Maths'] + df['Science'] + df['English']

# Calculate Average Marks
df['Average_Marks'] = df['Total_Marks'] / 3

# Define a grading function
def assign_grade(average_marks):
    if average_marks >= 90:
        return 'A'
    elif average_marks >= 80:
        return 'B'
    elif average_marks >= 70:
        return 'C'
    elif average_marks >= 60:
        return 'D'
    else:
        return 'F'

# Apply the grading function to create a 'Grade' column
df['Grade'] = df['Average_Marks'].apply(assign_grade)

print("\n--- Student Performance Metrics ---")
print("DataFrame with Total Marks, Average Marks, and Grade:")
display(df.head())

print("--- Descriptive Statistics ---")

# Descriptive statistics for numerical columns
print("\nSummary statistics for numerical columns:")
display(df.describe())

# Calculate mode for relevant columns (describe() doesn't include it)
print("\nMode for numerical columns:")
for col in ['Maths', 'Science', 'English', 'Attendance', 'Internal_Marks']:
    if col in df.columns:
        print(f"  {col}: {df[col].mode().tolist()}")

"""### Distribution of Marks"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set the style for the plots
sns.set_style("whitegrid")

# Create histograms for marks distribution
marks_columns = ['Maths', 'Science', 'English', 'Attendance', 'Internal_Marks']

plt.figure(figsize=(15, 10))
for i, col in enumerate(marks_columns):
    plt.subplot(2, 3, i + 1) # Arrange in 2 rows, 3 columns
    sns.histplot(df[col], kde=True, bins=10, color='skyblue')
    plt.title(f'{col} Distribution')
    plt.xlabel(col)
    plt.ylabel('Frequency')

plt.tight_layout()
plt.show()